FROM kalilinux/kali-linux-docker

ENV container docker

RUN apt-get update
RUN apt-get install metasploit-framework -y

RUN mkdir /usr/nmap_logstash

RUN curl https://raw.githubusercontent.com/nateshull/nmap_xml_to_json/master/nmap_xml_to_json.py > /usr/nmap_logstash/nmap_xml_to_json.py

RUN echo $'#!/bin/bash \n\
echo "running script"\n\
if [ "$DEBUG" == "true" ] \n\
then \n\
	echo "running nmap $NMAP_ARG -oX - | python3 /usr/nmap_logstash/nmap_xml_to_json.py | curl -H "x-nmap-target: $HEADER_INFO" http://$LOGSTASH_SERVER:$LOGSTASH_PORT --data-binary @- " \n\
fi \n\
if [ "$LOGSTASH_USER" = "" ] \n\
then \n\
	nmap $NMAP_ARG -oX - | python3 /usr/nmap_logstash/nmap_xml_to_json.py | curl -H "x-nmap-target: $SCAN_DESC" $LOGSTASH_SERVER --data-binary @- \n\
else \n\
	nmap $NMAP_ARG -oX - | python3 /usr/nmap_logstash/nmap_xml_to_json.py | curl -u $LOGSTASH_USER:$LOGSTASH_PASS -H "x-nmap-target: $SCAN_DESC" $LOGSTASH_SERVER --data-binary @- \n\
fi \n\
\n'\
> /usr/nmap_logstash/start_script.sh

ENV DEBUG="false"

ENV NMAP_ARG="-O 10.10.10.0/24 "

ENV LOGSTASH_SERVER="http://logstash:5000"

ENV LOGSTASH_USER=""

ENV LOGSTASH_PASS="Password"

ENV SCAN_DESC="NMapDocker"

RUN chmod -R 777 /usr/nmap_logstash/*

ENTRYPOINT /usr/nmap_logstash/start_script.sh
